### ISSUE TITLE
license etc

### ISSUE THREAD

**Issue by pythagoraswitch** [worldbank/DIME-LaTeX-Templates#2]
If you are going to make this repo public on WB account, you will need to add basic info (license, how to contribute, etc). MIT license is the most generous one and recommended. Let us know if you have any questions!

cc @dc-coder

**Comment by mrimal** [comment]
Would the MIT license work for a non-software product as well ? Thanks!

**Comment by pythagoraswitch** [comment]
good point! realized this is mostly tutorial materials. What we did in https://github.com/worldbank/ml4dev repo is to add MIT license and say text content is CC-BY. i.e. "All code is MIT licensed, and the text content is CC-BY."

**Comment by mrimal** [comment]
Did the same. Thanks.
